language: php

php:
    - 7.2

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

cache:
  directories:
   - $HOME/.composer/cache/files
   - vendor

script:
    - vendor/bin/phpunit --coverage-clover coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
    email: virodriguez37@poligran.edu.co
